/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRecurringIndexRouteImport } from './routes/_authenticated/recurring/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedRecurringNewRouteImport } from './routes/_authenticated/recurring/new'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices/$id'
import { Route as AuthenticatedExpensesNewRouteImport } from './routes/_authenticated/expenses/new'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients/new'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients/$id'
import { Route as AuthenticatedInvoicesIdPreviewRouteImport } from './routes/_authenticated/invoices/$id.preview'
import { Route as AuthenticatedInvoicesIdEditRouteImport } from './routes/_authenticated/invoices/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecurringIndexRoute =
  AuthenticatedRecurringIndexRouteImport.update({
    id: '/recurring/',
    path: '/recurring/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecurringNewRoute =
  AuthenticatedRecurringNewRouteImport.update({
    id: '/recurring/new',
    path: '/recurring/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesNewRoute =
  AuthenticatedExpensesNewRouteImport.update({
    id: '/expenses/new',
    path: '/expenses/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesIdPreviewRoute =
  AuthenticatedInvoicesIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedInvoicesIdRoute,
  } as any)
const AuthenticatedInvoicesIdEditRoute =
  AuthenticatedInvoicesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedInvoicesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRouteWithChildren
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/recurring/new': typeof AuthenticatedRecurringNewRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/recurring/': typeof AuthenticatedRecurringIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/invoices/$id/preview': typeof AuthenticatedInvoicesIdPreviewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRouteWithChildren
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/recurring/new': typeof AuthenticatedRecurringNewRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/recurring': typeof AuthenticatedRecurringIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/invoices/$id/preview': typeof AuthenticatedInvoicesIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRouteWithChildren
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/recurring/new': typeof AuthenticatedRecurringNewRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/recurring/': typeof AuthenticatedRecurringIndexRoute
  '/_authenticated/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/_authenticated/invoices/$id/preview': typeof AuthenticatedInvoicesIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reports'
    | '/settings'
    | '/auth/verify'
    | '/clients/$id'
    | '/clients/new'
    | '/expenses/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/recurring/new'
    | '/clients/'
    | '/expenses/'
    | '/invoices/'
    | '/recurring/'
    | '/invoices/$id/edit'
    | '/invoices/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reports'
    | '/settings'
    | '/auth/verify'
    | '/'
    | '/clients/$id'
    | '/clients/new'
    | '/expenses/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/recurring/new'
    | '/clients'
    | '/expenses'
    | '/invoices'
    | '/recurring'
    | '/invoices/$id/edit'
    | '/invoices/$id/preview'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/auth/verify'
    | '/_authenticated/'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/new'
    | '/_authenticated/expenses/new'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/recurring/new'
    | '/_authenticated/clients/'
    | '/_authenticated/expenses/'
    | '/_authenticated/invoices/'
    | '/_authenticated/recurring/'
    | '/_authenticated/invoices/$id/edit'
    | '/_authenticated/invoices/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurring/': {
      id: '/_authenticated/recurring/'
      path: '/recurring'
      fullPath: '/recurring/'
      preLoaderRoute: typeof AuthenticatedRecurringIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurring/new': {
      id: '/_authenticated/recurring/new'
      path: '/recurring/new'
      fullPath: '/recurring/new'
      preLoaderRoute: typeof AuthenticatedRecurringNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/new': {
      id: '/_authenticated/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AuthenticatedExpensesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/$id/preview': {
      id: '/_authenticated/invoices/$id/preview'
      path: '/preview'
      fullPath: '/invoices/$id/preview'
      preLoaderRoute: typeof AuthenticatedInvoicesIdPreviewRouteImport
      parentRoute: typeof AuthenticatedInvoicesIdRoute
    }
    '/_authenticated/invoices/$id/edit': {
      id: '/_authenticated/invoices/$id/edit'
      path: '/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof AuthenticatedInvoicesIdEditRouteImport
      parentRoute: typeof AuthenticatedInvoicesIdRoute
    }
  }
}

interface AuthenticatedInvoicesIdRouteChildren {
  AuthenticatedInvoicesIdEditRoute: typeof AuthenticatedInvoicesIdEditRoute
  AuthenticatedInvoicesIdPreviewRoute: typeof AuthenticatedInvoicesIdPreviewRoute
}

const AuthenticatedInvoicesIdRouteChildren: AuthenticatedInvoicesIdRouteChildren =
  {
    AuthenticatedInvoicesIdEditRoute: AuthenticatedInvoicesIdEditRoute,
    AuthenticatedInvoicesIdPreviewRoute: AuthenticatedInvoicesIdPreviewRoute,
  }

const AuthenticatedInvoicesIdRouteWithChildren =
  AuthenticatedInvoicesIdRoute._addFileChildren(
    AuthenticatedInvoicesIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedExpensesNewRoute: typeof AuthenticatedExpensesNewRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRouteWithChildren
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedRecurringNewRoute: typeof AuthenticatedRecurringNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedRecurringIndexRoute: typeof AuthenticatedRecurringIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedExpensesNewRoute: AuthenticatedExpensesNewRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRouteWithChildren,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedRecurringNewRoute: AuthenticatedRecurringNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedRecurringIndexRoute: AuthenticatedRecurringIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
